In [3]:
import pandas as pd

In [5]:
df = pd.read_excel("airsen.xlsx")

In [10]:
df.head()

,ID_Vol,Date_Vol,Heure_Départ,Heure_Arrivée,Aéroport_Départ,Aéroport_Arrivée,Aeroports_Desservis,Distance_km,Durée_vol_min,Numéro_Avion,...,Prénom_Pilote,Sexe,Date_Naissance,Âge_Pilote,Licence_Pilote,Heures_Vol_Pilote,Salaire_Pilote,Statut_Vol,Météo,Nombre_Passagers
0,V0001,18/05/2024,02:15,06:58,Dubaï,Abidjan,Dubaï - Tunis - Abidjan,3614,283,AV646,...,Moussa,Homme,20/09/1987,38,ATPL,3376,8415990,Annulé,Orage,64
1,V0002,15/05/2024,21:00,22:41,Casablanca,Istanbul,Casablanca - Bruxelles - Istanbul,5260,101,AV984,...,Aliou,Homme,29/01/1994,32,ATPL,3116,9326310,Annulé,Orage,169
2,V0003,11/07/2024,07:00,12:38,Bamako,Casablanca,Bamako - Casablanca,6252,338,AV727,...,Cheikh,Homme,02/01/1991,35,ATPL,5498,5034734,Annulé,Vent,266
3,V0004,04/08/2024,23:00,00:38,Abidjan,Bamako,Abidjan - Bamako,6962,98,AV814,...,Ibrahima,Homme,26/05/1989,36,CPL,2649,4361564,Retardé,Nuageux,154
4,V0005,09/02/2024,01:00,03:13,Paris,Dakar,Paris - Abidjan - Bruxelles - Dakar,2767,133,AV612,...,Khadija,Femme,09/07/1992,33,ATPL,11505,2796190,À l’heure,Clair,234

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Vol               3000 non-null   str
 1   Date_Vol             3000 non-null   str
 2   Heure_Départ         3000 non-null   str
 3   Heure_Arrivée        3000 non-null   str
 4   Aéroport_Départ      3000 non-null   str
 5   Aéroport_Arrivée     3000 non-null   str
 6   Aeroports_Desservis  3000 non-null   str
 7   Distance_km          3000 non-null   int64
 8   Durée_vol_min        3000 non-null   int64
 9   Numéro_Avion         3000 non-null   str
 10  Type_Avion           3000 non-null   str
 11  Fabricant_Avion      3000 non-null   str
 12  Prix_Avion           3000 non-null   int64
 13  Capacité_Avion       3000 non-null   int64
 14  Compagnie            3000 non-null   str
 15  ID_Pilote            3000 non-null   str
 16  Nom_Pilote           3000 non-null   str
 17  Prénom_Pilote        3000 non-null   str
 18  Sexe                 3000 non-null   str
 19  Date_Naissance       3000 non-null   str
 20  Âge_Pilote           3000 non-null   int64
 21  Licence_Pilote       3000 non-null   str
 22  Heures_Vol_Pilote    3000 non-null   int64
 23  Salaire_Pilote       3000 non-null   int64
 24  Statut_Vol           3000 non-null   str
 25  Météo                3000 non-null   str
 26  Nombre_Passagers     3000 non-null   int64
dtypes: int64(8), str(19)
memory usage: 632.9 KB

In [ ]:
df.describe()

,Distance_km,Durée_vol_min,Prix_Avion,Capacité_Avion,Âge_Pilote,Heures_Vol_Pilote,Salaire_Pilote,Nombre_Passagers
count,3000.000000,3000.000000,3.000000e+03,3000.000000,3000.000000,3000.000000,3.000000e+03,3000.000000
mean,3700.311333,228.600000,1.836783e+08,210.353333,44.436667,8391.295333,5.997116e+06,130.412000
std,1858.804394,97.639755,1.079951e+08,78.009211,9.514243,3746.373000,2.340680e+06,64.793274
min,501.000000,60.000000,2.500000e+07,70.000000,28.000000,2004.000000,2.000143e+06,50.000000
25%,2068.000000,145.000000,1.000000e+08,170.000000,36.000000,5123.750000,3.968534e+06,69.000000
50%,3744.500000,227.000000,2.500000e+08,250.000000,44.000000,8231.500000,5.967153e+06,120.000000
75%,5271.750000,315.000000,2.800000e+08,280.000000,53.000000,11670.000000,8.023476e+06,172.000000
max,6998.000000,400.000000,3.200000e+08,300.000000,61.000000,14998.000000,9.991151e+06,300.000000